version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ticketing-backend:latest
    container_name: ticketing-backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/var/task/app
    entrypoint: []
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - ticketing-network

networks:
  ticketing-network:
    driver: bridge
